alias sb="subl ./"
alias envconf="subl ~/Shell/env.sh"
alias aliasconf="subl ~/Shell/alias.sh"
alias szsh="source ~/.zshrc"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
